version: '3.8'

services:
  # Servicio PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: quimbayaeval-db
    environment:
      POSTGRES_DB: quimbayaeval
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - quimbayaeval-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
    driver: local

networks:
  quimbayaeval-network:
    driver: bridge
