-- Tablas adicionales para tests (no tienen entidades JPA)
-- Hibernate crea: users, cursos, evaluaciones, pqrs
-- Este script crea las tablas restantes del schema

CREATE TABLE IF NOT EXISTS preguntas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id INTEGER,
    enunciado VARCHAR(1000) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    puntuacion DECIMAL(5,2) DEFAULT 1.0,
    orden INTEGER,
    opciones_json VARCHAR(2000),
    respuesta_correcta_json VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS submissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id INTEGER NOT NULL,
    estudiante_id INTEGER NOT NULL,
    fecha_inicio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_envio TIMESTAMP,
    respuestas_json VARCHAR(4000),
    intento_numero INTEGER DEFAULT 1,
    estado VARCHAR(50) NOT NULL DEFAULT 'Borrador',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS resultados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id INTEGER NOT NULL UNIQUE,
    puntuacion_total DECIMAL(5,2),
    puntuacion_maxima DECIMAL(5,2),
    porcentaje DECIMAL(5,2),
    estado_aprobacion VARCHAR(50),
    observaciones VARCHAR(1000),
    fecha_resultado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inscripciones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id INTEGER,
    curso_id INTEGER,
    fecha_inscripcion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(estudiante_id, curso_id)
);

CREATE TABLE IF NOT EXISTS calificaciones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id INTEGER NOT NULL,
    pregunta_id INTEGER NOT NULL,
    puntuacion_obtenida DECIMAL(5,2),
    puntuacion_maxima DECIMAL(5,2),
    retroalimentacion VARCHAR(1000),
    calificado_por_id INTEGER,
    fecha_calificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(submission_id, pregunta_id)
);
