package com.quimbayaeval.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.quimbayaeval.dao.UserDao;
import com.quimbayaeval.model.Pregunta;
import com.quimbayaeval.model.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest
@AutoConfigureMockMvc
@Sql(statements = {
    "CREATE TABLE IF NOT EXISTS preguntas (" +
    "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
    "evaluacion_id INTEGER NOT NULL, " +
    "enunciado TEXT NOT NULL, " +
    "tipo VARCHAR(50) NOT NULL, " +
    "puntuacion DECIMAL(5, 2) DEFAULT 1.0, " +
    "orden INTEGER, " +
    "opciones_json TEXT, " +
    "respuesta_correcta_json TEXT, " +
    "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
    "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)"
}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
class PreguntaControllerIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private UserDao userDao;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private org.springframework.jdbc.core.JdbcTemplate jdbcTemplate;

    private String token;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @BeforeEach
    void setUp() throws Exception {
        // Limpiar datos en orden correcto
        jdbcTemplate.execute("SET REFERENTIAL_INTEGRITY FALSE");
        jdbcTemplate.execute("DELETE FROM preguntas");
        jdbcTemplate.execute("DELETE FROM evaluaciones");
        jdbcTemplate.execute("DELETE FROM cursos");
        jdbcTemplate.execute("DELETE FROM users");
        jdbcTemplate.execute("SET REFERENTIAL_INTEGRITY TRUE");

        User prof = new User("Prof", "prof3@example.com", passwordEncoder.encode("pwd"), "maestro");
        userDao.save(prof);
        // create evaluation
        jdbcTemplate.update("INSERT INTO cursos (codigo,nombre,profesor_id,created_at) VALUES ('X','X',?,CURRENT_TIMESTAMP)", prof.getId());
        Integer cursoId = jdbcTemplate.queryForObject("SELECT id FROM cursos LIMIT 1", Integer.class);
        jdbcTemplate.update("INSERT INTO evaluaciones (nombre,curso_id,profesor_id,tipo,publicada,estado,created_at) VALUES ('E',?,?,'Quiz',false,'Borrador',CURRENT_TIMESTAMP)", cursoId, prof.getId());

        String loginJson = "{\"email\":\"prof3@example.com\",\"password\":\"pwd\",\"role\":\"maestro\"}";
        String content = mockMvc.perform(post("/api/auth/login")
                .contentType(MediaType.APPLICATION_JSON)
                .content(loginJson))
                .andExpect(status().isOk())
                .andReturn().getResponse().getContentAsString();
        token = objectMapper.readTree(content).path("data").path("token").asText();
    }

    @Test
    void createAndRetrievePregunta() throws Exception {
        // get evaluacion id
        Integer evalId = jdbcTemplate.queryForObject("SELECT id FROM evaluaciones LIMIT 1", Integer.class);
        Pregunta p = new Pregunta();
        p.setEvaluacionId(evalId);
        p.setEnunciado("¿1+1?");
        p.setTipo("respuesta_corta");
        p.setPuntuacion(1.0);
        String json = objectMapper.writeValueAsString(p);
        mockMvc.perform(post("/api/preguntas")
                .header("Authorization","Bearer " + token)
                .contentType(MediaType.APPLICATION_JSON)
                .content(json))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.data.evaluacionId").value(evalId));

        mockMvc.perform(get("/api/preguntas/evaluacion/"+evalId)
                .header("Authorization","Bearer " + token))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data[0].enunciado").value("¿1+1?"));
    }
}
